$(document).ready(function(){
    $('.first').owlCarousel({
        loop:true,
        margin:10,
        dots:false,
        autoplay:true,
        autoplayTimeout:1500,
        autoplayHoverPause:false,
        fluidSpeed:true,
        autoplaySpeed:false,
        smartSpeed:250,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:2
            },
            1000:{
                items:2
            }
        }
    });
});